all:
  hosts:
    web:
      ansible_host: "{{ lookup('env', 'TF_PUBLIC_IP') }}"
      ansible_user: ec2-user
      ansible_ssh_private_key_file: "{{ lookup('env', 'TF_PEM_PATH') }}"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
